runtime: python37

instance_class: B8

handlers:
  # This configures Google App Engine to serve the files in the app's static
  # directory.
- url: /static
  static_dir: static

basic_scaling: 
  max_instances: 2
  idle_timeout: 40m

env_variables:
    SECRET_KEY: open2020
    MONGO_DB_URI: mongodb+srv://scraper-admin:6PoJcLydol0XuLdX@freecluster.jg51j.mongodb.net/myFirstDatabase?authSource=admin&replicaSet=atlas-yp5iu3-shard-0&w=majority&readPreference=primary&appname=MongoDB%20Compass&retryWrites=true&ssl=true
    GOOGLE_CLOUD_PROJECT: curbo-dev
    SUBSCRIPTION_NAME: projects/curbo-dev/subscriptions/extract-meli-rd-sub
